# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(789, 507)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 360, 91, 16))
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 390, 161, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 80, 121, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ToDataUI = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ToDataUI.setObjectName("ToDataUI")
        self.verticalLayout.addWidget(self.ToDataUI)
        self.BeginMain = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.BeginMain.setObjectName("BeginMain")
        self.verticalLayout.addWidget(self.BeginMain)
        self.ToConfigUI = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ToConfigUI.setObjectName("ToConfigUI")
        self.verticalLayout.addWidget(self.ToConfigUI)
        self.ToAnalysisUI = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ToAnalysisUI.setObjectName("ToAnalysisUI")
        self.verticalLayout.addWidget(self.ToAnalysisUI)
        self.OutputAnswer = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.OutputAnswer.setObjectName("OutputAnswer")
        self.verticalLayout.addWidget(self.OutputAnswer)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.MainGraph = QtWidgets.QGroupBox(Dialog)
        self.MainGraph.setGeometry(QtCore.QRect(270, 10, 511, 491))
        self.MainGraph.setCheckable(False)
        self.MainGraph.setObjectName("MainGraph")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "实时分析："))
        self.label_2.setText(_translate("Dialog", "计算用时："))
        self.label_3.setText(_translate("Dialog", "迭代步数："))
        self.label_4.setText(_translate("Dialog", "当前总长："))
        self.ToDataUI.setText(_translate("Dialog", "地图载入"))
        self.BeginMain.setText(_translate("Dialog", "开始执行"))
        self.ToConfigUI.setText(_translate("Dialog", "参数配置"))
        self.ToAnalysisUI.setText(_translate("Dialog", "路径评估"))
        self.OutputAnswer.setText(_translate("Dialog", "结果导出"))
        self.label_5.setText(_translate("Dialog", "垃圾转运路径规划系统"))
        self.MainGraph.setTitle(_translate("Dialog", "可视化路径"))
