# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 315)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 190, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(140, 260, 141, 21))
        self.label_2.setObjectName("label_2")
        self.Warning = QtWidgets.QLabel(Dialog)
        self.Warning.setGeometry(QtCore.QRect(61, 24, 271, 171))
        self.Warning.setText("")
        self.Warning.setScaledContents(True)
        self.Warning.setObjectName("Warning")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "警告：未完成前置步骤"))
        self.label_2.setText(_translate("Dialog", "暂无法执行该操作"))
